
spring:
  profiles: dev

  datasource:
    url: "jdbc:mysql://localhost:3306/evochia_dev"
    username: "evochia_developer"
    password: "apassword"
---
spring:
  profiles: test
  datasource:
    url: "jdbc:mysql://localhost:3306/evochia_test"
    username: "evochia_developer"
    password: "apassword"
